### ISSUE TITLE
player statue not working

### ISSUE THREAD

**Issue by anthony1204** [Zailer43/FZMM-Mod#50]
i followed all the instructions but end up with a small corner. i am on 1.20.4 of the mod

**Comment by Zailer43** [comment]
can you reproduce the error in singleplayer?

**Comment by Zailer43** [comment]
You need to provide more information on how to reproduce the bug, but the bug you describe is likely one that mainly occurs in multiplayer, where some plugins remove a tag from armor stands when they are placed by a dispenser. Sometimes using the automatic placer (right-click with the player statue’s shulker) has fixed it

If the issue is reproducible in singleplayer, please reopen the issue with more information
