### ISSUE TITLE
heads turn to steve heads

### ISSUE THREAD

**Issue by Pikldoornob** [Zailer43/FZMM-Mod#55]
sometimes when you get a head from the head generator it just turns into a steve head

**Comment by Zailer43** [comment]
Without further details, I can assume the following:

1. Random error
   If the error occurs randomly and resolves itself after some time, it is likely due to an issue with [Mineskin](https://mineskin.org), the API used by FZMM to upload the skin. This type of error is already known and appears as a warning in the logs. I need to add a warning for users when this happens.

2. Error with a specific skin
   If the error always occurs with a particular skin, then it is not a known bug and may require further investigation. In this case, please attach logs and the skin if possible.

3. Bug with some plugins:
   There is another external issue where certain plugins, such as PlotSquared, remove the NBT data from the head if you try to obtain it while looking at a block in an area without permissions. To avoid this problem, obtain the head without pointing at any block or get it in an area with permissions.

**Comment by exkc** [comment]
i have the same issue and i am pretty sure it is cursed the antil cheat on the server in my case.(the server has its own command for head and it has the same issue)

**Comment by Zailer43** [comment]
There is missing information about what causes this bug, but in the [latest release](https://modrinth.com/mod/fzmm/version/0.2.14), there should be an error alert indicating the cause, except for the third case mentioned above

If it persists, you can reopen the bug
